services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend_service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
    ports:
      - "8000:8000"
  frontend:
    build: ./
    container_name: frontend_service
    ports:
      - "3000:3000"

volumes:
  db_data:
