version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    

volumes:
  postgres_data:
