version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "8080:80"
    depends_on:
      - db

# services:
#   postgres:
#     container_name: postgres
#     image: postgres
#     environment:
#       POSTGRES_USER: ddf_developer
#       POSTGRES_PASSWORD: divine@2022
#       PGDATA: /data/postgres
#     volumes:
#       - postgres:/data/postgres
#     ports:
#       - "5432:5432"
#     networks:
#       - postgres
#     restart: unless-stopped
 
#   pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: divinedryfruitsofficial@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: divine@2022
#       PGADMIN_CONFIG_SERVER_MODE: 'False'
#     volumes:
#       - pgadmin:/var/lib/pgadmin
#     ports:
#       - "5050:80"
#     networks:
#       - postgres
#     restart: unless-stopped
 
# networks:
#   postgres:
#     driver: bridge
 
# volumes:
#   postgres:
#   pgadmin: